Repository CarsOk/ADSO2558427EQUIPO1WEB, pull requests merged in 2023-11, with the labels that each got.

#104 update_shops
  proyecto/proyecto3/app/assets/stylesheets/application.css.scss
  proyecto/proyecto3/app/controllers/orders_controller.rb
  proyecto/proyecto3/app/views/cart/_order_form.html.erb
  proyecto/proyecto3/app/views/cart/_orderables.html.erb
  proyecto/proyecto3/app/views/inventories/index.html.erb
  proyecto/proyecto3/app/views/layouts/_navigation.html.erb
  proyecto/proyecto3/app/views/layouts/_topnavbar.erb
  proyecto/proyecto3/app/views/products/show.html.erb
  proyecto/proyecto3/app/views/shops/index.html.erb
Labels: bug

#107 Reinicio Diario de Órdenes y Exportación a Excel
  proyecto/proyecto3/Gemfile
  proyecto/proyecto3/Gemfile.lock
  proyecto/proyecto3/app/assets/images/header-profile.png
  proyecto/proyecto3/app/assets/stylesheets/application.css.scss
  proyecto/proyecto3/app/assets/stylesheets/base/chat.scss
  proyecto/proyecto3/app/assets/stylesheets/base/variables.scss
  proyecto/proyecto3/app/assets/stylesheets/cards.scss
  proyecto/proyecto3/app/assets/stylesheets/cart.scss
  proyecto/proyecto3/app/assets/stylesheets/order_items.scss
  proyecto/proyecto3/app/assets/stylesheets/orders.scss
  proyecto/proyecto3/app/assets/stylesheets/products.scss
  proyecto/proyecto3/app/controllers/cart_controller.rb
  proyecto/proyecto3/app/controllers/inventories_controller.rb
  proyecto/proyecto3/app/controllers/orders_controller.rb
  proyecto/proyecto3/app/controllers/products_controller.rb
  proyecto/proyecto3/app/controllers/sessions_controller.rb
  proyecto/proyecto3/app/controllers/shops_controller.rb
  proyecto/proyecto3/app/helpers/application_helper.rb
  proyecto/proyecto3/app/models/inventory.rb
  proyecto/proyecto3/app/models/order.rb
  proyecto/proyecto3/app/models/product.rb
  proyecto/proyecto3/app/views/cart/_orders_list.html.erb
  proyecto/proyecto3/app/views/inventories/index.html.erb
  proyecto/proyecto3/app/views/inventories/new.html.erb
  proyecto/proyecto3/app/views/layouts/_navigation.html.erb
  proyecto/proyecto3/app/views/layouts/application.html.erb
  proyecto/proyecto3/app/views/orders/accounting_report.html.erb
  proyecto/proyecto3/app/views/orders/generate_invoice.pdf.erb
  proyecto/proyecto3/app/views/orders/index.html.erb
  proyecto/proyecto3/app/views/orders/orders_of_the_day.html.erb
  proyecto/proyecto3/app/views/products/_form.html.erb
  proyecto/proyecto3/app/views/products/index.html.erb
  proyecto/proyecto3/app/views/products/show.html.erb
  proyecto/proyecto3/app/views/sessions/index.html.erb
  proyecto/proyecto3/app/views/shops/index.html.erb
  proyecto/proyecto3/config/application.rb
  proyecto/proyecto3/config/environments/development.rb
  proyecto/proyecto3/config/initializers/carrierwave.rb
  proyecto/proyecto3/config/initializers/mime_types.rb
  proyecto/proyecto3/config/routes.rb
  proyecto/proyecto3/config/schedule.rb
  proyecto/proyecto3/db/migrate/20231110023112_add_order_number_to_orders.rb
  proyecto/proyecto3/db/migrate/20231115231529_add_sold_count_to_products.rb
  proyecto/proyecto3/db/migrate/20231118015141_change_product_id_type_in_inventories.rb
  proyecto/proyecto3/db/migrate/20231118021541_add_foreign_key_to_inventories.rb
  proyecto/proyecto3/db/schema.rb
  proyecto/proyecto3/lib/assets/plantilla.xlsx
  proyecto/proyecto3/lib/scripts/reset_orders_counter.rb
Labels: bug, enhancement

#109 settings on the documentation page
  docs/css/apple/app.min.css
  docs/css/apple/user-manual.css
  docs/img/Diagrama_ER_01.jpeg
  docs/img/caso-de-uso-g-inventario.jpg
  docs/img/caso-de-uso-g-productos.jpg
  docs/img/caso-de-uso-login.jpg
  docs/img/caso-de-uso-sign-in.jpg
  docs/img/caso-de-uso-toma-pedido.jpg
  docs/img/diagrama_er.jpg
  docs/img/diagrama_flujo.jpeg
  docs/img/pages/Captura de pantalla 2023-11-14 120946.png
  docs/img/pages/Captura de pantalla 2023-11-14 121000.png
  docs/img/pages/Captura de pantalla 2023-11-14 121031.png
  docs/img/pages/Captura de pantalla 2023-11-14 121058.png
  docs/img/pages/Captura de pantalla 2023-11-14 121118.png
  docs/img/pages/Captura de pantalla 2023-11-14 121130.png
  docs/img/pages/Captura de pantalla 2023-11-14 121141.png
  docs/img/pages/Captura de pantalla 2023-11-14 121254.png
  docs/img/pages/Captura de pantalla 2023-11-14 121335.png
  docs/img/pages/Captura de pantalla 2023-11-14 121355.png
  docs/img/pages/Captura de pantalla 2023-11-14 121416.png
  docs/img/pages/Captura de pantalla 2023-11-14 121436.png
  docs/img/pages/Captura de pantalla 2023-11-14 121502.png
  docs/img/pages/Captura de pantalla 2023-11-14 121518.png
  docs/img/pages/Captura de pantalla 2023-11-14 121616.png
  docs/img/pages/carrito-compras.jpg
  docs/img/pages/login.jpg
  docs/img/pages/mis-productos.jpg
  docs/img/pages/pago-productos.jpg
  docs/img/pages/pantalla-principal.jpg
  docs/img/pages/seleccion-carrito-compras.jpg
  docs/img/pages/sign-in.jpg
  docs/index.html
  docs/movil.html
  docs/pages/technical-manual.html
  docs/pages/user-manual.html
  docs/web.html
Labels: documentation
