Repository CarsOk/ADSO2558427EQUIPO1WEB, pull requests merged in 2023-10, with the labels that each got.

#79 create database pg
  proyecto/proyecto3/Gemfile
  proyecto/proyecto3/Gemfile.lock
  proyecto/proyecto3/config/database.yml
  proyecto/proyecto3/db/schema.rb
Labels: enhancement

#83 update
  proyecto/proyecto3/app/controllers/cards_controller.rb
  proyecto/proyecto3/app/controllers/shops_controller.rb
  proyecto/proyecto3/app/views/layouts/shops.html.erb
  proyecto/proyecto3/app/views/shops/show.html.erb
Labels: bug, enhancement

#84 update
  proyecto/proyecto3/Gemfile
  proyecto/proyecto3/Gemfile.lock
  proyecto/proyecto3/app/controllers/application_controller.rb
  proyecto/proyecto3/app/controllers/products_controller.rb
  proyecto/proyecto3/app/models/user.rb
  proyecto/proyecto3/app/policies/application_policy.rb
  proyecto/proyecto3/app/policies/user_policy.rb
  proyecto/proyecto3/app/views/layouts/_navigation.html.erb
  proyecto/proyecto3/db/migrate/20231015182806_add_admin_to_users.rb
  proyecto/proyecto3/db/schema.rb
  proyecto/proyecto3/test/policies/user_policy_test.rb
Labels: enhancement

#86 Inclusion de Plantilla toma de pedidos y arreglos de Bug's
  proyecto/proyecto3/app/controllers/products_controller.rb
  proyecto/proyecto3/app/models/product.rb
  proyecto/proyecto3/app/views/products/_form.html.erb
  proyecto/proyecto3/app/views/products/index.html.erb
  proyecto/proyecto3/app/views/shops/index.html.erb
  proyecto/proyecto3/config/environments/development.rb
  proyecto/proyecto3/db/migrate/20231011023926_add_category_to_products.rb
  proyecto/proyecto3/db/schema.rb
  proyecto/proyecto3/public/uploads/product/image/8/hamburguesa.jpg
  proyecto/proyecto3/public/uploads/product/image/9/descarga.jpeg
Labels: bug, enhancement

#88 Conexion a S3 para el procesamiento de las imagenes
  proyecto/proyecto3/Gemfile
  proyecto/proyecto3/Gemfile.lock
  proyecto/proyecto3/app/uploaders/image_uploader.rb
  proyecto/proyecto3/config/initializers/carrierwave.rb
  proyecto/proyecto3/db/schema.rb
Labels: bug

#94 Implementación de inventario
  proyecto/proyecto3/app/assets/stylesheets/application.css.scss
  proyecto/proyecto3/app/controllers/inventories_controller.rb
  proyecto/proyecto3/app/helpers/inventories_helper.rb
  proyecto/proyecto3/app/helpers/inventory_helper.rb
  proyecto/proyecto3/app/models/inventory.rb
  proyecto/proyecto3/app/models/product.rb
  proyecto/proyecto3/app/views/inventories/_form.html.erb
  proyecto/proyecto3/app/views/inventories/edit.html.erb
  proyecto/proyecto3/app/views/inventories/index.html.erb
  proyecto/proyecto3/app/views/inventories/new.html.erb
  proyecto/proyecto3/app/views/layouts/_navigation.html.erb
  proyecto/proyecto3/app/views/shops/index.html.erb
  proyecto/proyecto3/config/routes.rb
  proyecto/proyecto3/db/migrate/20231024050630_create_inventories.rb
  proyecto/proyecto3/db/schema.rb
  proyecto/proyecto3/test/controllers/inventories_controller_test.rb
  proyecto/proyecto3/test/controllers/inventory_controller_test.rb
  proyecto/proyecto3/test/fixtures/inventories.yml
  proyecto/proyecto3/test/models/inventory_test.rb
Labels: enhancement
