Repository CarsOk/ADSO2558427EQUIPO1WEB, pull requests merged in 2023-09, with the labels that each got.

#47 document entry diagram
  docs/diagramas/diagrama_flujo.jpeg
Labels: documentation

#51 Ajuste de pagina de documentación
  docs/img/LogoCurb.png
  docs/img/burger.png
  docs/img/fondo.png
  docs/index.html
Labels: documentation

#52 Creación y diseño de tabla de entidad relación
  docs/img/diagrama_er.jpg
  docs/index.html
Labels: documentation

#53 Implementación de diagrama de flujo para el nuevo proyecto
  docs/img/diagrama_flujo.jpeg
  docs/index.html
Labels: documentation

#54 Correction of documentation
  docs/diagramas/diagrama_flujo.jpeg
  docs/index.html
Labels: bug

#58 DIseño de Mockup para proyecto nuevo
  docs/img/Dashboard_Black.jpeg
  docs/img/Dashboard_White.jpeg
  docs/img/Login_Black.jpeg
  docs/img/Login_White.jpeg
  docs/index.html
Labels: documentation

#61 entry of documentation on software requirements
  docs/index.html
Labels: documentation

#64 Subida de archivos de documentación - Issue #48
  docs/img/Diagrama_ER_01.jpeg
  docs/index.html
Labels: documentation

#72 pestaña para almacenar toda la documentación proyecto móvil y cambios en la interfaz
  docs/css/apple/app.min.css
  docs/index.html
  docs/movil.html
  docs/web.html
Labels: documentation

#71 dashboard
  plantilla.html
  proyecto/proyecto3/Gemfile
  proyecto/proyecto3/Gemfile.lock
  proyecto/proyecto3/app/assets/config/manifest.js
  proyecto/proyecto3/app/assets/javascript/application.js
  proyecto/proyecto3/app/javascript/channels/consumer.js
  proyecto/proyecto3/app/javascript/channels/index.js
  proyecto/proyecto3/app/javascript/packs/application.js
  proyecto/proyecto3/app/views/devise/sessions/new.html.erb
  proyecto/proyecto3/app/views/layouts/_header.html.erb
  proyecto/proyecto3/app/views/layouts/_sidebar.html.erb
  proyecto/proyecto3/app/views/layouts/application.html.erb
  proyecto/proyecto3/app/views/layouts/empty.html.erb
  proyecto/proyecto3/app/views/sessions/index.html.erb
  proyecto/proyecto3/config/routes.rb
  proyecto/proyecto3/package.json
  proyecto/proyecto3/yarn.lock
Labels: enhancement

#69 Dashboard
  proyecto/proyecto3/Gemfile
  proyecto/proyecto3/Gemfile.lock
  proyecto/proyecto3/app/assets/config/manifest.js
  proyecto/proyecto3/app/assets/javascripts/application.js
  proyecto/proyecto3/app/assets/javascripts/channels/.keep
  proyecto/proyecto3/app/assets/javascripts/inspinia.js
  proyecto/proyecto3/app/assets/stylesheets/animate/animate.css
  proyecto/proyecto3/app/assets/stylesheets/application.css.scss
  proyecto/proyecto3/app/assets/stylesheets/base/badges_labels.scss
  proyecto/proyecto3/app/assets/stylesheets/base/base.scss
  proyecto/proyecto3/app/assets/stylesheets/base/buttons.scss
  proyecto/proyecto3/app/assets/stylesheets/base/chat.scss
  proyecto/proyecto3/app/assets/stylesheets/base/custom.scss
  proyecto/proyecto3/app/assets/stylesheets/base/elements.scss
  proyecto/proyecto3/app/assets/stylesheets/base/glyphicons.scss
  proyecto/proyecto3/app/assets/stylesheets/base/landing.scss
  proyecto/proyecto3/app/assets/stylesheets/base/md-skin.scss
  proyecto/proyecto3/app/assets/stylesheets/base/media.scss
  proyecto/proyecto3/app/assets/stylesheets/base/metismenu.scss
  proyecto/proyecto3/app/assets/stylesheets/base/mixins.scss
  proyecto/proyecto3/app/assets/stylesheets/base/navigation.scss
  proyecto/proyecto3/app/assets/stylesheets/base/pages.scss
  proyecto/proyecto3/app/assets/stylesheets/base/rtl.scss
  proyecto/proyecto3/app/assets/stylesheets/base/sidebar.scss
  proyecto/proyecto3/app/assets/stylesheets/base/skins.scss
  proyecto/proyecto3/app/assets/stylesheets/base/spinners.scss
  proyecto/proyecto3/app/assets/stylesheets/base/theme-config.scss
  proyecto/proyecto3/app/assets/stylesheets/base/top_navigation.scss
  proyecto/proyecto3/app/assets/stylesheets/base/typography.scss
  proyecto/proyecto3/app/assets/stylesheets/base/variables.scss
  proyecto/proyecto3/app/assets/stylesheets/style.scss
  proyecto/proyecto3/app/controllers/sessions_controller.rb
  proyecto/proyecto3/app/helpers/application_helper.rb
  proyecto/proyecto3/app/javascript/channels/consumer.js
  proyecto/proyecto3/app/javascript/channels/index.js
  proyecto/proyecto3/app/javascript/packs/application.js
  proyecto/proyecto3/app/views/layouts/_footer.html.erb
  proyecto/proyecto3/app/views/layouts/_navigation.html.erb
  proyecto/proyecto3/app/views/layouts/_topnavbar.erb
  proyecto/proyecto3/app/views/layouts/application.html.erb
  proyecto/proyecto3/app/views/layouts/empty.html.erb
  proyecto/proyecto3/app/views/sessions/home.html.erb
  proyecto/proyecto3/app/views/sessions/index.html.erb
  proyecto/proyecto3/app/views/sessions/ventas.html.erb
  proyecto/proyecto3/config/routes.rb
  proyecto/proyecto3/package.json
  proyecto/proyecto3/vendor/assets/javascripts/.keep
  proyecto/proyecto3/vendor/assets/javascripts/jquery/jquery-3.1.1.min.js
  proyecto/proyecto3/vendor/assets/javascripts/metisMenu/jquery.metisMenu.js
  proyecto/proyecto3/vendor/assets/javascripts/pace/pace.min.js
  proyecto/proyecto3/vendor/assets/javascripts/slimscroll/jquery.slimscroll.min.js
  proyecto/proyecto3/vendor/assets/stylesheets/animate/animate.css
  proyecto/proyecto3/yarn.lock
Labels: enhancement
